package main

import (
	"fmt"
	"io"
	"strings"
)

var helpTopics = map[string]string{
	"": `Run and administer Coworker Relay

Usage:
  coworker-relay <command> [options]
  coworker-relay help [command [subcommand]]
  coworker-relay <command> [subcommand] --help

Commands:
  serve                Start the Relay HTTPS service
  init                 Create a Compose deployment (interactive with no options)
  health               Check Relay availability
  version              Print coworker-relay version information (--version also works)
  backup               Download a consistent database backup
  restore              Restore a backup while Relay is stopped
  gc                   Run database garbage collection
  metrics              Show Relay operational metrics
  instance             Create and manage Coworker instances
  bans                 Inspect and remove source-IP bans
  cache                Inspect and purge the update cache
  help                 Show command help

Configuration:
  RELAY_URL=https://relay.example.com:8443
  RELAY_ADMIN_TOKEN=<shared administrator token>
  RELAY_CA_CERT=/path/to/private-ca.pem
  RELAY_CONFIG=.env  # optional; defaults to ./.env

Run "coworker-relay help <command>" for command details.
`,
	"serve": `Start the Coworker Relay HTTPS service

Usage:
  coworker-relay serve

The service reads RELAY_* environment variables. It first loads missing
RELAY_* values from RELAY_CONFIG, or from ./.env when RELAY_CONFIG is unset.
Explicit process environment values take precedence over the file.
`,
	"help": `Show coworker-relay help

Usage:
  coworker-relay help
  coworker-relay help <command>
  coworker-relay help <group> <subcommand>

The equivalent -h and --help flags may be placed after a command or
subcommand. Help is available without Relay configuration or network access.
`,
	"init": `Initialize a self-hosted Coworker Relay deployment

Usage:
  coworker-relay init
  coworker-relay init --public-url <https-origin> [options]

With no options, init starts an interactive setup wizard. For scripts and
non-terminal input, pass --public-url and the desired options explicitly.

Options:
  --dir <directory>          Deployment directory (default: coworker-relay-deploy)
  --public-url <origin>      Public HTTPS origin
  --external-port <port>     Published HTTPS port (default: 8443)
  --acme-domain <name>       ACME DNS name or public IP (defaults to URL host)
  --tls-cert <path>          Existing PEM certificate (requires --tls-key)
  --tls-key <path>           Existing PEM private key (requires --tls-cert)
  --image <reference>        Relay container image
  --force                    Replace files generated by an earlier init

Automatic ACME and an existing PEM certificate are mutually exclusive.
`,
	"health": `Check Relay availability

Usage:
  coworker-relay health

Calls the public Relay health endpoint. RELAY_URL is required.
`,
	"version": `Print coworker-relay version information

Usage:
  coworker-relay version
  coworker-relay --version

This command does not require Relay configuration or network access.
`,
	"backup": `Download a consistent Relay database backup

Usage:
  coworker-relay backup [--output <path>]

Options:
  --output <path>  Destination file; defaults to a timestamped .db file

RELAY_URL and RELAY_ADMIN_TOKEN are required. Existing files are not replaced.
`,
	"restore": `Restore a Relay database from a validated backup

Usage:
  coworker-relay restore --from <backup.db> --database <stopped-relay.db> [--force]

Options:
  --from <path>      Backup database to validate and restore
  --database <path>  Destination database of a stopped Relay
  --force            Preserve and replace an existing destination database

Stop Relay before restoring. This command does not contact Relay.
`,
	"gc": `Run Relay database garbage collection

Usage:
  coworker-relay gc

RELAY_URL and RELAY_ADMIN_TOKEN are required.
`,
	"metrics": `Show Relay operational metrics

Usage:
  coworker-relay metrics

RELAY_URL and RELAY_ADMIN_TOKEN are required.
`,
	"instance": `Create and manage Coworker instances

Usage:
  coworker-relay instance <subcommand> [options]

Subcommands:
  create               Create an instance and one-time pairing code
  list                 List instances
  revoke               Permanently revoke an instance
  rotate-credential    Rotate an instance tunnel credential
  update-auth          Change update-download authentication mode
  update-stats         Show update-client compatibility statistics

Run "coworker-relay help instance <subcommand>" for details.
`,
	"instance create": `Create a Coworker instance

Usage:
  coworker-relay instance create [--name <name>]

Options:
  --name <name>  Optional display name

Returns the instance identifier and a short-lived, one-time pairing code.
RELAY_URL and RELAY_ADMIN_TOKEN are required.
`,
	"instance list": `List Coworker instances

Usage:
  coworker-relay instance list

RELAY_URL and RELAY_ADMIN_TOKEN are required.
`,
	"instance revoke": `Permanently revoke a Coworker instance

Usage:
  coworker-relay instance revoke <instance_id>

Revocation disconnects the instance and invalidates its credential.
RELAY_URL and RELAY_ADMIN_TOKEN are required.
`,
	"instance rotate-credential": `Rotate a Coworker instance tunnel credential

Usage:
  coworker-relay instance rotate-credential <instance_id>

RELAY_URL and RELAY_ADMIN_TOKEN are required.
`,
	"instance update-auth": `Change an instance update-download authentication mode

Usage:
  coworker-relay instance update-auth <instance_id> <optional|required>

optional preserves anonymous compatibility for older Desktop versions.
required requires a valid communication Bearer token for every update request.
RELAY_URL and RELAY_ADMIN_TOKEN are required.
`,
	"instance update-stats": `Show update-client compatibility statistics for an instance

Usage:
  coworker-relay instance update-stats <instance_id>

Shows the anonymous and authenticated update aggregates used when deciding
whether to switch the instance to required update authentication.
RELAY_URL and RELAY_ADMIN_TOKEN are required.
`,
	"bans": `Inspect and remove Relay source-IP bans

Usage:
  coworker-relay bans <subcommand> [options]

Subcommands:
  list    List active bans
  remove  Remove a ban with an audit reason

Run "coworker-relay help bans <subcommand>" for details.
`,
	"bans list": `List active Relay source-IP bans

Usage:
  coworker-relay bans list [--instance <instance_id>]

Options:
  --instance <instance_id>  Limit results to one Coworker instance

RELAY_URL and RELAY_ADMIN_TOKEN are required.
`,
	"bans remove": `Remove a Relay source-IP ban

Usage:
  coworker-relay bans remove --instance <instance_id> --ip <ip> --reason <reason>

Options:
  --instance <instance_id>  Coworker instance
  --ip <ip>                  Banned source IP
  --reason <reason>          Required audit-log reason

RELAY_URL and RELAY_ADMIN_TOKEN are required.
`,
	"cache": `Inspect and purge the Relay update cache

Usage:
  coworker-relay cache <subcommand>

Subcommands:
  inspect  Show cache entries and usage
  purge    Remove cached update artifacts

Run "coworker-relay help cache <subcommand>" for details.
`,
	"cache inspect": `Show Relay update-cache entries and usage

Usage:
  coworker-relay cache inspect

RELAY_URL and RELAY_ADMIN_TOKEN are required.
`,
	"cache purge": `Remove Relay update-cache artifacts

Usage:
  coworker-relay cache purge

RELAY_URL and RELAY_ADMIN_TOKEN are required.
`,
}

var helpGroups = map[string]struct{}{
	"instance": {},
	"bans":     {},
	"cache":    {},
}

// handleHelp resolves all help requests before configuration loading or command
// dispatch. Its return value reports whether the invocation was a help request.
func handleHelp(args []string, output io.Writer) (bool, error) {
	if len(args) == 0 {
		return true, writeHelpTopic(output, "")
	}
	if args[0] == "help" {
		if len(args) == 1 ||
			(len(args) == 2 && (args[1] == "-h" || args[1] == "--help")) {
			return true, writeHelpTopic(output, "")
		}
		topic := strings.Join(args[1:], " ")
		return true, writeHelpTopic(output, topic)
	}
	if args[0] == "-h" || args[0] == "--help" {
		return true, writeHelpTopic(output, "")
	}

	helpAt := -1
	for index, arg := range args {
		if arg == "-h" || arg == "--help" {
			helpAt = index
			break
		}
	}
	if helpAt >= 0 {
		topic, err := helpTopicForInvocation(args[:helpAt])
		if err != nil {
			return true, err
		}
		return true, writeHelpTopic(output, topic)
	}

	if len(args) == 1 {
		if _, group := helpGroups[args[0]]; group {
			return true, writeHelpTopic(output, args[0])
		}
	}
	return false, nil
}

func helpTopicForInvocation(args []string) (string, error) {
	if len(args) == 0 {
		return "", nil
	}
	command := args[0]
	if _, group := helpGroups[command]; group {
		if len(args) == 1 || strings.HasPrefix(args[1], "-") {
			return command, nil
		}
		topic := command + " " + args[1]
		if _, exists := helpTopics[topic]; !exists {
			return "", unknownHelpTopic(topic)
		}
		return topic, nil
	}
	if _, exists := helpTopics[command]; !exists || strings.Contains(command, " ") {
		return "", unknownHelpTopic(command)
	}
	return command, nil
}

func writeHelpTopic(output io.Writer, topic string) error {
	text, exists := helpTopics[topic]
	if !exists {
		return unknownHelpTopic(topic)
	}
	_, err := fmt.Fprint(output, text)
	return err
}

func unknownHelpTopic(topic string) error {
	return fmt.Errorf(
		"unknown help topic %q; run \"coworker-relay --help\" to list commands",
		topic,
	)
}
