"""Route participant-bound inbound communication directly to active bubbles."""

from __future__ import annotations

from typing import TYPE_CHECKING

from loguru import logger

from coworker.core.autonomy import AutonomyLevel, AutonomyScope
from coworker.core.types import IncomingEvent

if TYPE_CHECKING:
    from coworker.agent.bubble import BubbleStore


# These events are generated by Coworker itself rather than by a communication
# participant.  They must continue through the main loop even if a bubble has
# accidentally been bound to the same placeholder participant id.
_INTERNAL_SOURCES = {
    "alarm",
    "bubble",
    "code_job",
    "compress_memory",
    "system",
    "task_reminder",
}


class BubbleMessageRouter:
    """An InboxWatcher interceptor for normal, participant-bound bubbles.

    A message is consumed only when exactly one running bubble matches it.  An
    unmatched or ambiguous message remains on the normal inbox, preserving the
    existing main-thread behavior and avoiding accidental cross-task routing.
    """

    def __init__(self, store: BubbleStore) -> None:
        self._store = store

    def __call__(self, event: IncomingEvent) -> bool:
        if event.source in _INTERNAL_SOURCES or not event.participant_id:
            return False

        bubble = self._store.find_active_for_message(
            participant_id=event.participant_id,
            conversation_id=event.conversation_id,
        )
        if bubble is None:
            return False

        autonomy = bubble.brain.autonomy if bubble.brain is not None else None
        incoming_trigger = event.wake_level or AutonomyLevel.REACTIVE
        required_trigger = max(
            (bubble.origin_trigger, incoming_trigger),
            key=lambda level: level.rank,
        )
        if autonomy is not None and not autonomy.allows(
            AutonomyScope.BUBBLE,
            trigger=required_trigger,
        ):
            logger.info(
                "Kept inbound message from {}{} on the durable main inbox because "
                "bubble {} is policy-paused",
                event.participant_id,
                f"/{event.conversation_id}" if event.conversation_id else "",
                bubble.id,
            )
            return False

        # put_nowait is intentional: InboxWatcher interceptors are synchronous,
        # and an asyncio.Queue without a maxsize cannot block here.
        bubble.enqueue_nowait(event)
        logger.info(
            "Routed inbound message from {}{} directly to bubble {}",
            event.participant_id,
            f"/{event.conversation_id}" if event.conversation_id else "",
            bubble.id,
        )
        return True
